name: Scrape and Upload to Google Sheets

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:

  scrape-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas selenium gspread google-auth
      run: |
        python main.py
